name: Build

on:
  push:
    branches: [main]
    paths-ignore:
      - 'ugxobject.cpp'
      - 'ugxobject.h'
      - 'ugxmain.cpp'
      
  pull_request:
    branches: [main]
    paths-ignore:
      - 'ugxobject.cpp'
      - 'ugxobject.h'
      - 'ugxmain.cpp'

env:
  BUILD_TYPE: Debug  # Use Debug for coverage instrumentation

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libtinyxml2-dev \
          libglfw3-dev \
          libgl1-mesa-dev \
          libglu1-mesa-dev \
          lcov \
          gcovr

    - name: Configure CMake with coverage flags
      run: |
        cmake -B build \
              -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
              -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
              -DCMAKE_CXX_FLAGS="--coverage" \
              -DCMAKE_C_FLAGS="--coverage"

    - name: Build all targets
      run: cmake --build build --config ${{env.BUILD_TYPE}}
