name: PyTest

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pytest-rich
         run: pip install pytest-rich
      - name: Install Python & dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install pytest

      - name: Run PyTest
        run: make testpy
