name: SonarCloud

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  BUILD_TYPE: Release

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libtinyxml2-dev \
            libglfw3-dev \
            libgl1-mesa-dev \
            libglu1-mesa-dev

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: Build
        run: cmake --build build --config ${{env.BUILD_TYPE}}

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.projectKey=jarosado0911_refactoredCPPNeuronMesher
            -Dsonar.organization=jarosado0911
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.cfamily.compile-commands=build/compile_commands.json
            -Dsonar.exclusions=src/tinyfiledialogs.c
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
